PBL-SHINHODONG/back-end

.github/ISSUE_TEMPLATE/issue-template.md, .github/PULL_REQUEST_TEMPLATE/pull-request-template.md, .gitignore, app/crud/places.py, app/database.py, app/main.py, app/models/places.py, app/models/users.py, app/routers/places.py, app/routers/users.py, app/schemas/places.py, app/schemas/users.py, requirements.txt
---
title: feat: place entity 기능 개발 및 초기 파일 및 설정 구현
assignees: GomDue
---
- 크롤링한 데이터 전처리
- AWS RDS에 테이블 정의 및 데이터 삽입
- fastapi 프레임 워크 사용
- fastapi에서 AWS RDS에 접속 기능 개발
- place entity 기능 개발 - id로 장소에 대한 정보 반환
- place entity 기능 개발 - 이름으로 장소에 대한 정보 반환
- place entity 기능 개발 - id로 x, y 좌표 반환
- place entity 기능 개발 - 여러가지 쿼리를 통한 검색
- place 관련 api 및 스키마 구현
=> feat: place entity 기능 개발 및 초기 파일 및 설정 구현

.github/workflows/github-actions.yml
---
title: docs: github actions 추가
assignees: 
---
- github actions 추가
Issue number: #3
=> docs: github actions 추가

app/crud/places.py, app/models/places.py, app/routers/places.py, app/schemas/places.py
---
title: 스키마 변경으로 인한 place API 수정 및 추가
---
- Place 스키마 수정으로 인한 수정
- /places 호출 시 네이버와 카카오에서 수집한 데이터 반환(없다면 Null로 표시)
- 데이터 반환을 위한 NaverPlaceInfoResponse와 KakaoPlaceInfoResponse DAO 구현
- 데이터 반환을 위한 get_naver_place 및 get_kakao_place API 구현
- 데이터 반환을 위한 get_naver_place_info 및 get_kakao_place_info 함수 구현
- /places의 limit 설정
=> feat: 스키마 변경으로 인한 place API 수정 및 추가

app/crud/places.py, app/dependencies.py, app/routers/places.py, app/schemas/places.py, requirements.txt
---
title: x, y 좌표를 위도 경도로 변환하는 로직 추가
---
- x, y 좌표를 위도 경도로 변환하는 toLatLng() 함수 추가
- 좌표 변환을 해주는 pyproj 패키지 추가
=> feat: x, y 좌표를 위도 경도로 변환하는 로직 추가

app/crud/users.py, app/crud/visitedplaces.py, app/main.py, app/models/places.py, app/models/users.py, app/models/visitedplaces.py, app/routers/places.py, app/routers/users.py, app/routers/visitedplaces.py, app/schemas/users.py, app/schemas/visitedplaces.py
---
title: user entity 기능 개발 및 visited_place 기능 개발
assignees: GomDue
---
- user entity 기능 개발 - id로 사용자 정보 반환
- user entity 기능 개발 - 로그인 기능
- user entity 기능 개발 - 회원가입 기능
- visited_place entity 기능 개발 - user id로 해당 사용자가 방문했던 장소들 반환
- visited_place entity 기능 개발 - user id로 사용자가 방문을 안했다면 user id와 place id 저장, 방문 했다면 visit_count 1 증가
- user 관련 API, DAO, 스키마 구현
- visited_place 관련 API, DAO, 스키마 구현
Issue number:
=> feat: user entity 기능 개발 및 visited_place 기능 개발

app/dependencies.py
---
title: pyproj 코드 수정
---
- pyproj 코드 수정
Issue number: #2
=> fix: pyproj 코드 수정

app/crud/places.py
---
title: fix: pyproj 위도 경도 출력 반대 현상 해결
---
- 기존의 pyproj 는 경도, 위도 순으로 값을 리턴
- 하지만 본 시스템에서는 위도, 경도 순으로 사용하므로 수정
Issue number:
=> fix: pyproj 위도 경도 출력 반대 현상 해결

.github/workflows/github-actions.yml, app/crud/places.py, app/database.py, app/dependencies.py, app/main.py, app/models/dataset.py, app/routers/places.py, requirements.txt
---
title: feat: 군집화 Model API 구현
---
- 군집화 Model API 구현
- Hugging Face 를 통한 Model 적재 -> Token 필요
- 환경변수로 인한 Github Actions 수정
- lifespan을 사용해 서버가 시작하기 전에 Model 및 필요한 파일 load
- get_place_recommend() 함수 구현
=> feat: 군집화 Model API 구현

requirements.txt
---
title: fix: 패키지 수정
---
- 누락된 패키지 추가 - kmodes 패지
Issue number:
=> fix: 패키지 수정

app/crud/places.py, app/crud/users.py, app/crud/visitedplaces.py, app/database.py, app/routers/places.py, app/routers/users.py, app/routers/visitedplaces.py
---
title: fix: DB Transaction error
---
- 아래의 에러코드와 같은 DB Transaction error 해결
- sqlalchemy.exc.PendingRollbackError: Can't reconnect until invalid transaction is rolled back. Please rollback() fully before proceeding (Background on this error at: https://sqlalche.me/e/20/8s2b)
=> fix: DB Transaction error

app/schemas/users.py
---
title: fix:user id issue
---
- users id 반환 추가
Issue number:
=> fix:user id issue

app/crud/places.py, app/schemas/places.py
---
title: feat:response시 place id도 반환되도록 추가
---
- response시 place id도 반환되도록 추가
=> feat:response시 place id도 반환되도록 추가

app/crud/menus.py, app/main.py, app/models/menus.py, app/models/places.py, app/routers/menus.py, app/schemas/menus.py, app/schemas/visitedplaces.py
---
title: Menu Entity 기능 개발
assignees: GomDue
---
- place id를 통해 해당하는 가게의 메뉴 리스트를 반환
Issue number: #18
=> feat: Menu Entity 기능 개발

app/crud/menus.py, app/crud/places.py, app/crud/reviews.py, app/main.py, app/models/places.py, app/models/reviews.py, app/models/users.py, app/routers/reviews.py, app/schemas/reviews.py, app/schemas/users.py
---
title: Review Entity 기능 개발
---
- place id를 통해 해당하는 가게의 리뷰 반환
Issue number: #20
=> feat: Review Entity 기능 개발

app/crud/places.py
---
title: fix: get_places 메서드 수정
---
- get_places 메서드 수정
- 리뷰 수와 평점을 기준으로 정렬되지 않았던 문제점 해결
Issue number: #2
=> fix: get_places 메서드 수정

app/crud/search.py, app/main.py, app/routers/search.py, app/schemas/search.py
---
title: feat: 장소 및 메뉴 검색 기능 추가
---
- 장소 이름이나 메뉴 이름 일부를 입력하면 관련된 검색 결과 반환
Issue number: #2 #18
=> feat: 장소 및 메뉴 검색 기능 추가

app/crud/places.py, app/models/places.py
---
title: 카테고리 테이블 생성 및 컬럼 이름 변경
assignees: 
---
- 카테고리 테이블 생성 및 컬럼 이름 변경
Issue number:
=> 카테고리 테이블 생성 및 컬럼 이름 변경

app/crud/places.py, app/dependencies.py, app/routers/places.py, app/schemas/users.py
---
title: 
assignees: 
---
- 
Issue number:
=> 컨텐츠 기반 필터링 & 필터링 함수

app/main.py
---
title: fix: CPU로 모델 로드
assignees: GomDue
---
- CPU로 모델 로드 하도록 수정
=> fix: CPU로 모델 로드

app/crud/places.py, app/dependencies.py
---
title: 
assignees: 
---
- 
Issue number:
=> 사용자 방문 장소를 기반으로 한 컨텐츠 필터링
